// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPISample.Data;

namespace WebAPISample.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20201101160430_2")]
    partial class _2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAPISample.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Actors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Director")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rating")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovieId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Actors = "Leonardo DiCaprio, Matt Damon, Mark Wahlberg, Jack Nicholson, Vera Farmiga",
                            Director = "Martin Scorsese",
                            Genre = "Drama",
                            ImageURL = "https://i.pinimg.com/originals/86/f9/d1/86f9d1a47d81531f1e12e343d7a6ae0e.png",
                            Rating = "8.5",
                            Summary = "South Boston cop Billy Costigan (Leonardo DiCaprio) goes under cover to infiltrate the organization of gangland chief Frank Costello (Jack Nicholson). As Billy gains the mobster's trust, a career criminal named Colin Sullivan (Matt Damon) infiltrates the police department and reports on its activities to his syndicate bosses. When both organizations learn they have a mole in their midst, Billy and Colin must figure out each other's identities to save their own lives.",
                            Title = "The Departed",
                            Year = "2006"
                        },
                        new
                        {
                            MovieId = 2,
                            Actors = "Christian Bale, Gary Oldman, Heath Ledger, Michael Caine, Morgan Freeman",
                            Director = "Christopher Nolan",
                            Genre = "Drama",
                            ImageURL = "https://i.pinimg.com/originals/28/1d/03/281d03d7e0fae42cf27ebf513c00c6eb.jpg",
                            Rating = "9",
                            Summary = "With the help of allies Lt. Jim Gordon (Gary Oldman) and DA Harvey Dent (Aaron Eckhart), Batman (Christian Bale) has been able to keep a tight lid on crime in Gotham City. But when a vile young criminal calling himself the Joker (Heath Ledger) suddenly throws the town into chaos, the caped Crusader begins to tread a fine line between heroism and vigilantism.",
                            Title = "The Dark Knight",
                            Year = "2008"
                        },
                        new
                        {
                            MovieId = 3,
                            Actors = "Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page, Tom Hardy, Cillian Murphy",
                            Director = "Christopher Nolan",
                            Genre = "Drama",
                            ImageURL = "https://i.pinimg.com/originals/77/bb/6d/77bb6d11954d639e10affff6565b213a.jpg",
                            Rating = "8.8",
                            Summary = "Dom Cobb (Leonardo DiCaprio) is a thief with the rare ability to enter people's dreams and steal their secrets from their subconscious. His skill has made him a hot commodity in the world of corporate espionage but has also cost him everything he loves. Cobb gets a chance at redemption when he is offered a seemingly impossible task: Plant an idea in someone's mind. If he succeeds, it will be the perfect crime, but a dangerous enemy anticipates Cobb's every move.",
                            Title = "Inception",
                            Year = "2010"
                        },
                        new
                        {
                            MovieId = 4,
                            Actors = "Seth Rogen, James Franco, Danny McBride, Amber Heard, Gary Cole",
                            Director = "David Gordon Green",
                            Genre = "Comedy",
                            ImageURL = "https://i.pinimg.com/originals/8c/f2/4a/8cf24aa1b78365ea504eb5948470bfd4.jpg",
                            Rating = "2008",
                            Summary = "Stoner Dale Denton's (Seth Rogen) enjoyment of a rare strain of marijuana may prove fatal when he drops his roach in a panic after witnessing a murder. Upon learning that the fancy weed can be traced back to them, Dale and his dealer (James Franco) go on the lam, with a dangerous drug lord (Gary Cole) and crooked cop (Rosie Perez) hot on their heels.",
                            Title = "Pineapple Express",
                            Year = "2008"
                        },
                        new
                        {
                            MovieId = 5,
                            Actors = "Bruce Willis, Alan Rickman, Bonnie Bedelia, Reginald VelJohnson, William Atherton",
                            Director = "John McTiernan",
                            Genre = "Action",
                            ImageURL = "https://2.bp.blogspot.com/-LrHDd4vdHHw/Tw6fI1XEoRI/AAAAAAAAAPY/ov2jgvNQt4k/w1200-h630-p-k-no-nu/poster-die-hard1resize.jpg",
                            Rating = "8.2",
                            Summary = "New York City policeman John McClane (Bruce Willis) is visiting his estranged wife (Bonnie Bedelia) and two daughters on Christmas Eve. He joins her at a holiday party in the headquarters of the Japanese-owned business she works for. But the festivities are interrupted by a group of terrorists who take over the exclusive high-rise, and everyone in it. Very soon McClane realizes that there's no one to save the hostages -- but him.",
                            Title = "Die Hard",
                            Year = "1988"
                        },
                        new
                        {
                            MovieId = 6,
                            Actors = "Mike Judge, Ron Livingston, Gary Cole, Jennifer Aniston, Stephen Root",
                            Director = "Mike Judge",
                            Genre = "Comedy / Dark comedy ",
                            ImageURL = "https://i.pinimg.com/originals/74/97/c9/7497c926fb7673de5e9e04f046f0715e.jpg",
                            Rating = "7.7",
                            Summary = "Corporate drone Peter Gibbons (Ron Livingston) hates his soul-killing job at software company Initech. While undergoing hypnotherapy, Peter is left in a blissful state when his therapist dies in the middle of their session. He refuses to work overtime, plays games at his desk and unintentionally charms two consultants into putting him on the management fast-track. When Peter's friends learn they're about to be downsized, they hatch a revenge plot against the company inspired by Superman III.",
                            Title = "Office Space",
                            Year = "1999"
                        },
                        new
                        {
                            MovieId = 7,
                            Actors = "Milla Jovovich, Bruce Willis, Gary Oldman, Chris Tucker, Ian Holm",
                            Director = "Luc Besson",
                            Genre = "Action / Sci-fi ",
                            ImageURL = "https://cdn.shopify.com/s/files/1/0969/9128/products/The_Fifth_Element_-_Luc_Besson_-_Tallenge_Hollywood_Minimalist_Movie_Poster_99b922a1-97ee-4f82-bfe9-97ffe30836ed.jpg?v=1549014210",
                            Rating = "7.7",
                            Summary = "In the 23rd century, a New York City cabbie, Korben Dallas (Bruce Willis), finds the fate of the world in his hands when Leeloo (Milla Jovovich) falls into his cab. As the embodiment of the fifth element, Leeloo needs to combine with the other four to keep the approaching Great Evil from destroying the world. Together with Father Vito Cornelius (Ian Holm) and zany broadcaster Ruby Rhod (Chris Tucker), Dallas must race against time and the wicked industrialist Zorg (Gary Oldman) to save humanity.",
                            Title = "The Fifth Element",
                            Year = "1997"
                        },
                        new
                        {
                            MovieId = 8,
                            Actors = "John Cusack, Minnie Driver, Dan Aykroyd, Joan Cusack, Jeremy Piven",
                            Director = "George Armitage",
                            Genre = "Romance / Comedy",
                            ImageURL = "https://i.etsystatic.com/5576899/r/il/46c3b7/1678388829/il_570xN.1678388829_fcgp.jpg",
                            Rating = "7.3",
                            Summary = "After assassin Martin Blank (John Cusack) has trouble focusing on his work, resulting in a failed assignment, he returns to his hometown, Grosse Point, Mich., for his 10-year high school reunion. There he meets Debi Newberry (Minnie Driver), an old girlfriend that he stood up for the prom. Martin's secretary (Joan Cusack) sets up a hit for him while he is in town, but Martin starts to reconsider his life. Meanwhile, he is hounded by an unstable rival hit man, Grocer (Dan Aykroyd).",
                            Title = "Grosse Pointe Blank",
                            Year = "1997"
                        },
                        new
                        {
                            MovieId = 9,
                            Actors = "Natalie Portman, Jean Reno, Gary Oldman, Danny Aiello, Michael Badalucco",
                            Director = "",
                            Genre = "Action / Drama",
                            ImageURL = "https://piecesofpaint.com/wp-content/uploads/2013/12/leon_the_professional_credits.jpg",
                            Rating = "8.5",
                            Summary = "Michael Badalucco",
                            Title = "The Professional",
                            Year = "1994"
                        },
                        new
                        {
                            MovieId = 10,
                            Actors = "Scarlett Johansson, Morgan Freeman, Amr Waked, Analeigh Tipton",
                            Director = "Luc Besson",
                            Genre = "Thriller / Action",
                            ImageURL = "https://i.pinimg.com/originals/e4/1c/7d/e41c7d86a30fc39e4532ea7dfe55e852.jpg",
                            Rating = "6.4",
                            Summary = "Lucy is a 2014 French science fiction action film written and directed by Luc Besson and produced by his wife Virginie Besson-Silla for his company EuropaCorp. It is an English-language film shot in Taipei, Paris, and New York City. It stars Scarlett Johansson, Morgan Freeman, Choi Min-sik, and Amr Waked.",
                            Title = "Lucy",
                            Year = "2014"
                        },
                        new
                        {
                            MovieId = 11,
                            Actors = "David Bowie, Jennifer Connelly ",
                            Director = "Jim Henson",
                            Genre = "Fantasy/Musical ",
                            ImageURL = "https://i.imgur.com/UQ8Fz.jpg",
                            Rating = "7.4",
                            Summary = "Teenage Sarah (Jennifer Connelly) journeys through a maze to recover her baby brother (Toby Froud) from a goblin king (David Bowie).",
                            Title = "Labyrinth",
                            Year = "1986"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
