// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPISample.Data;

namespace WebAPISample.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20201103101419_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAPISample.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Actors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Director")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rating")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovieId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Actors = "Starring: Leonardo DiCaprio, Matt Damon, Mark Wahlberg, Jack Nicholson, Vera Farmiga",
                            Director = "Director: Martin Scorsese",
                            Genre = "Drama",
                            ImageURL = "https://i.pinimg.com/originals/86/f9/d1/86f9d1a47d81531f1e12e343d7a6ae0e.png",
                            Rating = "🟊 8.5/10",
                            Summary = "South Boston cop Billy Costigan (Leonardo DiCaprio) goes under cover to infiltrate the organization of gangland chief Frank Costello (Jack Nicholson). As Billy gains the mobster's trust, a career criminal named Colin Sullivan (Matt Damon) infiltrates the police department and reports on its activities to his syndicate bosses. When both organizations learn they have a mole in their midst, Billy and Colin must figure out each other's identities to save their own lives.",
                            Title = "The Departed",
                            Year = "2006"
                        },
                        new
                        {
                            MovieId = 2,
                            Actors = "Christian Bale, Gary Oldman, Heath Ledger, Michael Caine, Morgan Freeman",
                            Director = "Director: Christopher Nolan",
                            Genre = "Drama",
                            ImageURL = "https://i.pinimg.com/originals/28/1d/03/281d03d7e0fae42cf27ebf513c00c6eb.jpg",
                            Rating = "🟊 9/10",
                            Summary = "With the help of allies Lt. Jim Gordon (Gary Oldman) and DA Harvey Dent (Aaron Eckhart), Batman (Christian Bale) has been able to keep a tight lid on crime in Gotham City. But when a vile young criminal calling himself the Joker (Heath Ledger) suddenly throws the town into chaos, the caped Crusader begins to tread a fine line between heroism and vigilantism.",
                            Title = "The Dark Knight",
                            Year = "2008"
                        },
                        new
                        {
                            MovieId = 3,
                            Actors = "Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page, Tom Hardy, Cillian Murphy",
                            Director = "Director: Christopher Nolan",
                            Genre = "Drama",
                            ImageURL = "https://i.pinimg.com/originals/77/bb/6d/77bb6d11954d639e10affff6565b213a.jpg",
                            Rating = "🟊 8.8/10",
                            Summary = "Dom Cobb (Leonardo DiCaprio) is a thief with the rare ability to enter people's dreams and steal their secrets from their subconscious. His skill has made him a hot commodity in the world of corporate espionage but has also cost him everything he loves. Cobb gets a chance at redemption when he is offered a seemingly impossible task: Plant an idea in someone's mind. If he succeeds, it will be the perfect crime, but a dangerous enemy anticipates Cobb's every move.",
                            Title = "Inception",
                            Year = "2010"
                        },
                        new
                        {
                            MovieId = 4,
                            Actors = "Seth Rogen, James Franco, Danny McBride, Amber Heard, Gary Cole",
                            Director = "Director:David Gordon Green",
                            Genre = "Comedy",
                            ImageURL = "https://i.pinimg.com/originals/8c/f2/4a/8cf24aa1b78365ea504eb5948470bfd4.jpg",
                            Rating = "🟊 6.9/10",
                            Summary = "Stoner Dale Denton's (Seth Rogen) enjoyment of a rare strain of marijuana may prove fatal when he drops his roach in a panic after witnessing a murder. Upon learning that the fancy weed can be traced back to them, Dale and his dealer (James Franco) go on the lam, with a dangerous drug lord (Gary Cole) and crooked cop (Rosie Perez) hot on their heels.",
                            Title = "Pineapple Express",
                            Year = "2008"
                        },
                        new
                        {
                            MovieId = 5,
                            Actors = "Bruce Willis, Alan Rickman, Bonnie Bedelia, Reginald VelJohnson, William Atherton",
                            Director = "Director:John McTiernan",
                            Genre = "Action",
                            ImageURL = "https://2.bp.blogspot.com/-LrHDd4vdHHw/Tw6fI1XEoRI/AAAAAAAAAPY/ov2jgvNQt4k/w1200-h630-p-k-no-nu/poster-die-hard1resize.jpg",
                            Rating = "🟊 8.2/10",
                            Summary = "New York City policeman John McClane (Bruce Willis) is visiting his estranged wife (Bonnie Bedelia) and two daughters on Christmas Eve. He joins her at a holiday party in the headquarters of the Japanese-owned business she works for. But the festivities are interrupted by a group of terrorists who take over the exclusive high-rise, and everyone in it. Very soon McClane realizes that there's no one to save the hostages -- but him.",
                            Title = "Die Hard",
                            Year = "1988"
                        },
                        new
                        {
                            MovieId = 6,
                            Actors = "Mike Judge, Ron Livingston, Gary Cole, Jennifer Aniston, Stephen Root",
                            Director = "Director:Mike Judge",
                            Genre = "Comedy / Dark comedy ",
                            ImageURL = "https://i.pinimg.com/originals/74/97/c9/7497c926fb7673de5e9e04f046f0715e.jpg",
                            Rating = "🟊 7.7/10",
                            Summary = "Corporate drone Peter Gibbons (Ron Livingston) hates his soul-killing job at software company Initech. While undergoing hypnotherapy, Peter is left in a blissful state when his therapist dies in the middle of their session. He refuses to work overtime, plays games at his desk and unintentionally charms two consultants into putting him on the management fast-track. When Peter's friends learn they're about to be downsized, they hatch a revenge plot against the company inspired by Superman III.",
                            Title = "Office Space",
                            Year = "1999"
                        },
                        new
                        {
                            MovieId = 7,
                            Actors = "Milla Jovovich, Bruce Willis, Gary Oldman, Chris Tucker, Ian Holm",
                            Director = "Director:Luc Besson",
                            Genre = "Action / Sci-fi ",
                            ImageURL = "https://cdn.shopify.com/s/files/1/0969/9128/products/The_Fifth_Element_-_Luc_Besson_-_Tallenge_Hollywood_Minimalist_Movie_Poster_99b922a1-97ee-4f82-bfe9-97ffe30836ed.jpg?v=1549014210",
                            Rating = "🟊 7.7/10",
                            Summary = "In the 23rd century, a New York City cabbie, Korben Dallas (Bruce Willis), finds the fate of the world in his hands when Leeloo (Milla Jovovich) falls into his cab. As the embodiment of the fifth element, Leeloo needs to combine with the other four to keep the approaching Great Evil from destroying the world. Together with Father Vito Cornelius (Ian Holm) and zany broadcaster Ruby Rhod (Chris Tucker), Dallas must race against time and the wicked industrialist Zorg (Gary Oldman) to save humanity.",
                            Title = "The Fifth Element",
                            Year = "1997"
                        },
                        new
                        {
                            MovieId = 8,
                            Actors = "John Cusack, Minnie Driver, Dan Aykroyd, Joan Cusack, Jeremy Piven",
                            Director = "Director:George Armitage",
                            Genre = "Romance / Comedy",
                            ImageURL = "https://i.etsystatic.com/5576899/r/il/46c3b7/1678388829/il_570xN.1678388829_fcgp.jpg",
                            Rating = "🟊 7.3/10",
                            Summary = "After assassin Martin Blank (John Cusack) has trouble focusing on his work, resulting in a failed assignment, he returns to his hometown, Grosse Point, Mich., for his 10-year high school reunion. There he meets Debi Newberry (Minnie Driver), an old girlfriend that he stood up for the prom. Martin's secretary (Joan Cusack) sets up a hit for him while he is in town, but Martin starts to reconsider his life. Meanwhile, he is hounded by an unstable rival hit man, Grocer (Dan Aykroyd).",
                            Title = "Grosse Pointe Blank",
                            Year = "1997"
                        },
                        new
                        {
                            MovieId = 9,
                            Actors = "Natalie Portman, Jean Reno, Gary Oldman, Danny Aiello, Michael Badalucco",
                            Director = "Director:Luc Besson",
                            Genre = "Action / Drama",
                            ImageURL = "https://piecesofpaint.com/wp-content/uploads/2013/12/leon_the_professional_credits.jpg",
                            Rating = "🟊8.5/10",
                            Summary = "Michael Badalucco",
                            Title = "The Professional",
                            Year = "1994"
                        },
                        new
                        {
                            MovieId = 10,
                            Actors = "Scarlett Johansson, Morgan Freeman, Amr Waked, Analeigh Tipton",
                            Director = "Director:Luc Besson",
                            Genre = "Thriller / Action",
                            ImageURL = "https://i.pinimg.com/originals/e4/1c/7d/e41c7d86a30fc39e4532ea7dfe55e852.jpg",
                            Rating = "🟊 6.4/10",
                            Summary = "Lucy is a 2014 French science fiction action film written and directed by Luc Besson and produced by his wife Virginie Besson-Silla for his company EuropaCorp. It is an English-language film shot in Taipei, Paris, and New York City. It stars Scarlett Johansson, Morgan Freeman, Choi Min-sik, and Amr Waked.",
                            Title = "Lucy",
                            Year = "2014"
                        },
                        new
                        {
                            MovieId = 11,
                            Actors = "Starring: David Bowie, Jennifer Connelly ",
                            Director = "Director: Jim Henson",
                            Genre = "Fantasy/Musical ",
                            ImageURL = "https://i.imgur.com/UQ8Fz.jpg",
                            Rating = "🟊 7.4/10",
                            Summary = "Teenage Sarah (Jennifer Connelly) journeys through a maze to recover her baby brother (Toby Froud) from a goblin king (David Bowie).",
                            Title = "Labyrinth",
                            Year = "1986"
                        },
                        new
                        {
                            MovieId = 12,
                            Actors = "Starring: Robert Downey, Jr., Chris Hemsworth, Chris Evans, Mark Ruffalo, Scarlett Johansson, Jeremy Renner, Tom Hiddleston",
                            Director = "Director: Joss Whedon",
                            Genre = "Action/Sci-fi ",
                            ImageURL = "https://i.imgur.com/rJyZuwc.jpg",
                            Rating = "🟊 8/10",
                            Summary = "When Thor's evil brother, Loki (Tom Hiddleston), gains access to the unlimited power of the energy cube called the Tesseract, Nick Fury (Samuel L. Jackson), director of S.H.I.E.L.D., initiates a superhero recruitment effort to defeat the unprecedented threat to Earth. Joining Fury's 'dream team' are Iron Man (Robert Downey Jr.), Captain America (Chris Evans), the Hulk (Mark Ruffalo), Thor (Chris Hemsworth), the Black Widow (Scarlett Johansson) and Hawkeye (Jeremy Renner).",
                            Title = "The Avengers",
                            Year = "2012"
                        },
                        new
                        {
                            MovieId = 13,
                            Actors = "Starring: Bruce Willis, Alan Rickman, Bonnie Bedelia, Reginald VelJohnson ",
                            Director = "Director: John McTiernan",
                            Genre = "Action/Thriller ",
                            ImageURL = "https://i.imgur.com/k3FvWcS.jpg",
                            Rating = "🟊 8.2/10",
                            Summary = "New York City policeman John McClane (Bruce Willis) is visiting his estranged wife (Bonnie Bedelia) and two daughters on Christmas Eve. He joins her at a holiday party in the headquarters of the Japanese-owned business she works for. But the festivities are interrupted by a group of terrorists who take over the exclusive high-rise, and everyone in it. Very soon McClane realizes that there's no one to save the hostages -- but him.",
                            Title = "Die Hard",
                            Year = "1988"
                        },
                        new
                        {
                            MovieId = 14,
                            Actors = "Starring: Malin Åkerman, Jackie Earle Haley, Patrick Wilson, Jeffrey Dean Morgan ",
                            Director = "Director: Zack Snyder",
                            Genre = "Action/Adventure ",
                            ImageURL = "https://i.imgur.com/rfxuSWh.jpg",
                            Rating = "🟊 7.6/10",
                            Summary = "In an alternate 1985 America, costumed superheroes are part of everyday life. When one of his former comrades is murdered, masked vigilante Rorschach (Jackie Earle Haley) uncovers a plot to kill and discredit all past and present superheroes. As he reconnects with his retired associates, only one of which has true powers, Rorschach glimpses a far-reaching conspiracy involving their shared past and catastrophic consequences for the world's future.",
                            Title = "Watchmen",
                            Year = "2009"
                        },
                        new
                        {
                            MovieId = 15,
                            Actors = "Starring: Keanu Reeves, Carrie-Anne Moss, Laurence Fishburne, Hugo Weaving ",
                            Director = "Directors: Lana Wachowski, Lilly Wachowski",
                            Genre = "Action/Sci-fi ",
                            ImageURL = "https://i.imgur.com/J7HKByA.jpg",
                            Rating = "🟊 8.7/10",
                            Summary = "Neo (Keanu Reeves) believes that Morpheus (Laurence Fishburne), an elusive figure considered to be the most dangerous man alive, can answer his question -- What is the Matrix? Neo is contacted by Trinity (Carrie-Anne Moss), a beautiful stranger who leads him into an underworld where he meets Morpheus. They fight a brutal battle for their lives against a cadre of viciously intelligent secret agents. It is a truth that could cost Neo something more precious than his life.",
                            Title = "The Matrix",
                            Year = "1999"
                        },
                        new
                        {
                            MovieId = 16,
                            Actors = "Starring: Linda Blair, Ellen Burstyn, Jason Miller, Max von Sydow ",
                            Director = "Director: William Friedkin",
                            Genre = "Horror/Supernatural ",
                            ImageURL = "https://i.imgur.com/i9NSYmz.png",
                            Rating = "🟊 8/10",
                            Summary = "One of the most profitable horror movies ever made, this tale of an exorcism is based loosely on actual events. When young Regan (Linda Blair) starts acting odd -- levitating, speaking in tongues -- her worried mother (Ellen Burstyn) seeks medical help, only to hit a dead end. A local priest (Jason Miller), however, thinks the girl may be seized by the devil. The priest makes a request to perform an exorcism, and the church sends in an expert (Max von Sydow) to help with the difficult job.",
                            Title = "The Exorcist",
                            Year = "1973"
                        },
                        new
                        {
                            MovieId = 17,
                            Actors = "Starring: Quentin Tarantino, Michael Madsen, Tim Roth, Steve Buscemi ",
                            Director = "Director: Quentin Tarantino",
                            Genre = "Crime ",
                            ImageURL = "https://i.imgur.com/1h11H0u.png",
                            Rating = "🟊 8.3/10",
                            Summary = "Six criminals with pseudonyms, and each strangers to one another, are hired to carry out a robbery. The heist is ambushed by police and the gang are forced to shoot their way out. At their warehouse rendezvous, the survivors, realising that they were set up, try to find the traitor in their midst.",
                            Title = "Reservoir Dogs",
                            Year = "1992"
                        },
                        new
                        {
                            MovieId = 18,
                            Actors = "Starring: Jeff Bridges, John Goodman, Steve Buscemi, Julianne Moore ",
                            Director = "Directors: Ethan Coen, Joel Coen",
                            Genre = "Comedy/Crime ",
                            ImageURL = "https://i.imgur.com/s1GHCJg.jpg",
                            Rating = "🟊 8.1/10",
                            Summary = "Jeff `The Dude' Leboswki is mistaken for Jeffrey Lebowski, who is The Big Lebowski. Which explains why he's roughed up and has his precious rug peed on. In search of recompense, The Dude tracks down his namesake, who offers him a job. His wife has been kidnapped and he needs a reliable bagman. Aided and hindered by his pals Walter Sobchak, a Vietnam vet, and Donny, master of stupidity.",
                            Title = "The Big Lebowski",
                            Year = "1998"
                        },
                        new
                        {
                            MovieId = 19,
                            Actors = "Starring: Mark Hamill, Carrie Fisher, Harrison Ford, Billy Dee Williams ",
                            Director = "Director: George Lucas",
                            Genre = "Sci-fi/Adventure ",
                            ImageURL = "https://i.imgur.com/two02c7.jpg",
                            Rating = "🟊 8.3/10",
                            Summary = "Luke Skywalker (Mark Hamill) battles horrible Jabba the Hut and cruel Darth Vader to save his comrades in the Rebel Alliance and triumph over the Galactic Empire. Han Solo (Harrison Ford) and Princess Leia (Carrie Fisher) reaffirm their love and team with Chewbacca, Lando Calrissian (Billy Dee Williams), the Ewoks and the androids C-3PO and R2-D2 to aid in the disruption of the Dark Side and the defeat of the evil emperor.",
                            Title = "Return of the Jedi",
                            Year = "1983"
                        },
                        new
                        {
                            MovieId = 20,
                            Actors = "Starring: Anthony Perkins, Janet Leigh, Vera Miles ",
                            Director = "Director: Alfred Hitchcock",
                            Genre = "Horror/Thriller ",
                            ImageURL = "https://i.imgur.com/Q2fA12o.jpg",
                            Rating = "🟊 8.5/10",
                            Summary = "Phoenix secretary Marion Crane (Janet Leigh), on the lam after stealing $40,000 from her employer in order to run away with her boyfriend, Sam Loomis (John Gavin), is overcome by exhaustion during a heavy rainstorm. Traveling on the back roads to avoid the police, she stops for the night at the ramshackle Bates Motel and meets the polite but highly strung proprietor Norman Bates (Anthony Perkins), a young man with an interest in taxidermy and a difficult relationship with his mother",
                            Title = "Psycho",
                            Year = "1960"
                        },
                        new
                        {
                            MovieId = 21,
                            Actors = "Starring: Cillian Murphy, Chris Evans, Rose Byrne, Michelle Yeoh ",
                            Director = "Director: Danny Boyle",
                            Genre = "Sci-fi/Adventure ",
                            ImageURL = "https://i.imgur.com/R4tMo51.jpg",
                            Rating = "🟊 7.2/10",
                            Summary = "In the not-too-distant future, Earth's dying sun spells the end for humanity. In a last-ditch effort to save the planet, a crew of eight men and women ventures into space with a device that could revive the star. However, an accident, a grave mistake and a distress beacon from a long-lost spaceship throw the crew and its desperate mission into a tailspin.",
                            Title = "Sunshine",
                            Year = "2007"
                        },
                        new
                        {
                            MovieId = 22,
                            Actors = "Starring: Ewan McGregor, Jonny Lee Miller, Robert Carlyle, Ewen Bremner ",
                            Director = "Director: Danny Boyle",
                            Genre = "Crime/Drama ",
                            ImageURL = "https://i.imgur.com/a6girSy.jpg",
                            Rating = "🟊 8.1/10",
                            Summary = "Heroin addict Mark Renton (Ewan McGregor) stumbles through bad ideas and sobriety attempts with his unreliable friends -- Sick Boy (Jonny Lee Miller), Begbie (Robert Carlyle), Spud (Ewen Bremner) and Tommy (Kevin McKidd). He also has an underage girlfriend, Diane (Kelly Macdonald), along for the ride. After cleaning up and moving from Edinburgh to London, Mark finds he can't escape the life he left behind when Begbie shows up at his front door on the lam, and a scheming Sick Boy follows.",
                            Title = "Trainspotting",
                            Year = "1996"
                        },
                        new
                        {
                            MovieId = 23,
                            Actors = "Starring: Matthew Modine, R. Lee Ermey, Vincent D'Onofrio ",
                            Director = "Director: Stanley Kubrick",
                            Genre = "War/Action ",
                            ImageURL = "https://i.imgur.com/Qg2sdYM.jpg",
                            Rating = "🟊 8.3/10",
                            Summary = "Stanley Kubrick's take on the Vietnam War follows smart-aleck Private Davis (Matthew Modine), quickly christened 'Joker' by his foul-mouthed drill sergeant (R. Lee Ermey), and pudgy Private Lawrence (Vincent D'Onofrio), nicknamed 'Gomer Pyle,' as they endure the rigors of basic training. Though Pyle takes a frightening detour, Joker graduates to the Marine Corps and is sent to Vietnam as a journalist, covering -- and eventually participating in -- the bloody Battle of Hué.",
                            Title = "Full Metal Jacket",
                            Year = "1987"
                        },
                        new
                        {
                            MovieId = 24,
                            Actors = "Starring: Josh Brolin, Javier Bardem, Tommy Lee Jones ",
                            Director = "Director: Ethan Coen, Joel Coen",
                            Genre = "Thriller/Crime ",
                            ImageURL = "https://i.imgur.com/GCqQHi4.jpg",
                            Rating = "🟊 8.1/10",
                            Summary = "While out hunting, Llewelyn Moss (Josh Brolin) finds the grisly aftermath of a drug deal. Though he knows better, he cannot resist the cash left behind and takes it with him. The hunter becomes the hunted when a merciless killer named Chigurh (Javier Bardem) picks up his trail. Also looking for Moss is Sheriff Bell (Tommy Lee Jones), an aging lawman who reflects on a changing world and a dark secret of his own, as he tries to find and protect Moss.",
                            Title = "No Country For Old Men",
                            Year = "2007"
                        },
                        new
                        {
                            MovieId = 25,
                            Actors = "Starring: Dominic Cooper, Benjamin Walker, Rufus Sewell ",
                            Director = "Director: Timur Bekmambetov",
                            Genre = "Horror/Action ",
                            ImageURL = "https://i.imgur.com/eXRhtuu.jpg",
                            Rating = "🟊 5.9/10",
                            Summary = "While still a boy, Abraham Lincoln loses his mother to a vampire's bite. He vows revenge, but fails in the attempt, narrowly escaping with his life. He is rescued by Henry (Dominic Cooper), a charismatic vampire hunter who instructs Abe in the fine art of dispatching bloodsuckers. Abe (Benjamin Walker) continues his fight against the undead well into adulthood and his presidency, making a last stand against the ultimate vampire foe (Rufus Sewell) on the eve of the Civil War's defining battle.",
                            Title = "Abraham Lincoln: Vampire Hunter",
                            Year = "2012"
                        },
                        new
                        {
                            MovieId = 26,
                            Actors = "Starring: Sigourney Weaver, Veronica Cartwright, Yaphet Kotto, Tom Skerritt ",
                            Director = "Director: Ridley Scott",
                            Genre = "Horror/Sci-fi ",
                            ImageURL = "https://i.imgur.com/KcpTFSg.jpg",
                            Rating = "🟊 8.4/10",
                            Summary = "In deep space, the crew of the commercial starship Nostromo is awakened from their cryo-sleep capsules halfway through their journey home to investigate a distress call from an alien vessel. The terror begins when the crew encounters a nest of eggs inside the alien ship. An organism from inside an egg leaps out and attaches itself to one of the crew, causing him to fall into a coma.",
                            Title = "Alien",
                            Year = "1979"
                        },
                        new
                        {
                            MovieId = 27,
                            Actors = "Starring: Michael J. Fox, Christopher Lloyd, Crispin Glover, Lea Thompson ",
                            Director = "Director: Robert Zemeckis",
                            Genre = "Sci-fi/Adventure ",
                            ImageURL = "https://i.imgur.com/TW7rYYS.jpg",
                            Rating = "🟊 8.5/10",
                            Summary = "In this 1980s sci-fi classic, small-town California teen Marty McFly (Michael J. Fox) is thrown back into the '50s when an experiment by his eccentric scientist friend Doc Brown (Christopher Lloyd) goes awry. Traveling through time in a modified DeLorean car, Marty encounters young versions of his parents (Crispin Glover, Lea Thompson), and must make sure that they fall in love or he'll cease to exist. Even more dauntingly, Marty has to return to his own time and save the life of Doc Brown.",
                            Title = "Back To The Future",
                            Year = "1985"
                        },
                        new
                        {
                            MovieId = 28,
                            Actors = "Starring: Harold Ramis, Dan Aykroyd, Bill Murray ",
                            Director = "Director: Ivan Reitman",
                            Genre = "Comedy/Fantasy ",
                            ImageURL = "https://i.imgur.com/VnCZNRI.jpg",
                            Rating = "🟊 7.8/10",
                            Summary = "After the members of a team of scientists (Harold Ramis, Dan Aykroyd, Bill Murray) lose their cushy positions at a university in New York City, they decide to become 'ghostbusters' to wage a high-tech battle with the supernatural for money. They stumble upon a gateway to another dimension, a doorway that will release evil upon the city. The Ghostbusters must now save New York from complete destruction.",
                            Title = "Ghostbusters",
                            Year = "1984"
                        },
                        new
                        {
                            MovieId = 29,
                            Actors = "Starring: Leonardo DiCaprio, Tom Hanks ",
                            Director = "Director: Steven Spielberg",
                            Genre = "Crime ",
                            ImageURL = "https://i.imgur.com/UbxmtSQ.jpg",
                            Rating = "🟊 8.1/10",
                            Summary = "Frank Abagnale, Jr. (Leonardo DiCaprio) worked as a doctor, a lawyer, and as a co-pilot for a major airline -- all before his 18th birthday. A master of deception, he was also a brilliant forger, whose skill gave him his first real claim to fame: At the age of 17, Frank Abagnale, Jr. became the most successful bank robber in the history of the U.S. FBI Agent Carl Hanratty (Tom Hanks) makes it his prime mission to capture Frank and bring him to justice, but Frank is always one step ahead of him.",
                            Title = "Catch Me If You Can",
                            Year = "2002"
                        },
                        new
                        {
                            MovieId = 30,
                            Actors = "Starring: Edward Norton, Brad Pitt, Helena Bonham Carter ",
                            Director = "Director: David Fincher",
                            Genre = "Drama/Thriller ",
                            ImageURL = "https://i.imgur.com/ylFHSxt.jpg",
                            Rating = "🟊 8.8/10",
                            Summary = "A depressed man (Edward Norton) suffering from insomnia meets a strange soap salesman named Tyler Durden (Brad Pitt) and soon finds himself living in his squalid house after his perfect apartment is destroyed. The two bored men form an underground club with strict rules and fight other men who are fed up with their mundane lives. Their perfect partnership frays when Marla (Helena Bonham Carter), a fellow support group crasher, attracts Tyler's attention.",
                            Title = "Fight Club",
                            Year = "1999"
                        },
                        new
                        {
                            MovieId = 31,
                            Actors = "Starring: Jake Gyllenhaal, Jena Malone, Maggie Gyllenhaal, Patrick Swayze ",
                            Director = "Director: Richard Kelly",
                            Genre = "Fantasy/Sci-fi ",
                            ImageURL = "https://i.imgur.com/6sOy4j0.jpg",
                            Rating = "🟊 8/10",
                            Summary = "During the presidential election of 1988, a teenager named Donnie Darko sleepwalks out of his house one night and sees a giant, demonic-looking rabbit named Frank, who tells him the world will end in 28 days. When Donnie returns home, he finds that a jet engine has crashed into his bedroom. Is Donnie living in a parallel universe, is he suffering from mental illness - or will the world really end?",
                            Title = "Donnie Darko",
                            Year = "2001"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
